def generated_initial_seed() -> U32:
  1

def generated_starting_gold() -> U32:
  0

def generated_starting_selected_hero() -> U32:
  0

def generated_starting_selection_confirmed() -> U32:
  1

def generated_starting_dungeon_level() -> U32:
  1

def generated_dungeon_level_increment_per_refill() -> U32:
  1

def generated_ultimate_charge_required() -> U32:
  6

def generated_ultimate_charge_per_move() -> U32:
  1
